extends:
  ./node_modules/s15e-javascript/.eslintrc.yml

env:
  browser: true
  es6: true
  node: true

parserOptions:
  ecmaFeatures:
    jsx: true

rules:
  indent:
    - off

  brace-style:
    - off
