language: node_js
node_js:
- 10
- 12
- 14
matrix:
  fast_finish: true
cache:
  directories:
  - "$HOME/.npm"
script:
  - jest --coverage
  - codecov
env:
  global:
    secure: opsyYeVGK3IEtQIwNGvKFEPhmD9rLUORKGku9Aie8Z2gAjSjTuX4PN6NF0EW+S/gffuItUcSneDnFl+TtdBmD36PDXlKjrbCGGGsmkB+4NKP3Dk1qOx7u+1NMlnW51m471NjQCyUPQqlIP2oALuolXWt9wQJVS+5pRi4T+UKdqu6tseEMdCndLeSzDQ15FpkVGYecxzQhYaDbjVCXvLONse8hVVWEaNI1MksrwoslFPHFW0feNJaYUrKz0ofP67Kbwu90HkwQmy3+cQA4DmmlHOFA+bgLhBoltXUaYMfZ/Fxjq2J7PeEXFAujWJKFvg3BjRDpKj5Ae0lupbx+SGeBoxUMH23RMPQKdm9NUOecz/pglseibGsdcd3AEjHNKxAeT+3qwBUACOl2jNcapkgqcRK/hu5mzUrn37xJQ3zOfyyBmiXjy8XojdFM7BDNLp4vPZbTy0NyvWbc2343Gx7K2yZR++XJwo4OKzo1AVv/JoPoAohCmbD0aDi/FDxBal0CjwIEUU8F/SfoiiF4m3CbHay65OM7s1tfbYtyod5JyPEm8HDZnsJ+MJn72nWCiQBfysQZJO3IoeNTrH4uz9JTH+6MQQhPzZ5v4bzxtJV1TIlzj/bDmBGIERK6Dm3q3Vr7GQeWVAZC92mBd/cJLanpmHMF9lDCMjOsWtdbWwlogw=
