language: node_js

node_js:
  - 6
  - 7

matrix:
  fast_finish: true

cache:
  yarn: true
  directories:
    - node_modules
notifications:
  slack:
    secure: GZyNocJahfdTBXJPoST/2iqLjFV4/pzG9i0ldwt45irBmCJ6zhtHF75RdqsChVzKPpCkCb+VpYF32UmFG5lzNxYAk4LrLdQioFP8tt3mtkO2pyTbwLlcbmj7REFn2wJ8ZnV08xjB8JVDOc3BRuzJZ1y6pssCHi1t4hS2D/jWs2F8kAK9HtPde8HjWUtdNtuuDl4129bJBKi9LW0mSDCG7KOsCXDIj1EmeRJuxxVkR5oCXd1LuA1xTjn/OvLz9xZkoIqpxkCGasEFS4/48Uq9a/ZM3fZU7KCzW5ltSI90P2ETnqn+B79/RTbQCAwoePE1eRiuiPbAcXd3SuY4VRPw4Bx6lFCMYglbcJYwEZ7PKu0CSC/NR/+6FxmMqx/iaChQHanbMn15/C1+av9280yXOwerozEQ++nIAL3QcOZj3F8DgWKXK+/hwXB1Ljywm3LnXCk0QUNEljVjbIH9TwaNUB8uKIEbgM2Va0SttXkW95APvCXhMUEmL0BD9CH0X6i8LuhW8I/2+bnB4AYWDfVRJx2B0FB5HIUlyHmKxdXg7+1JexnIvBpeGFyNLouE9az6OE8THfNlivEsk4UHOfcWl3kHZk2E0vTSqVR+nUOfxcKgwZV0If9ZV7JrcCEBDZ24ZiQ874MbUk0V4rNju9eZJvBb7zvngg+DjP7EVioIjVY=
