# http://www.appveyor.com/docs/appveyor-yml

clone_depth: 10

environment:
  matrix:
    - nodejs_version: 4
      platform: x64
    - nodejs_version: 4
      platform: x86
    - nodejs_version: 6
      platform: x64
    - nodejs_version: 6
      platform: x86
    - nodejs_version: 7
      platform: x64
    - nodejs_version: 7
      platform: x86

version: "{build}"
build: off
deploy: off

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm -g install npm@latest
  - node --version
  - npm --version
  - yarn || npm prune && npm install

test_script:
  - npm test

cache:
  - node_modules
  - "%LOCALAPPDATA%/Yarn"
